name: Test repo dispatch

on:
  workflow_call:
    inputs:
      tenant:
        required: true
        type: string
      ref:
        required: true
        type: string
jobs:
  test_workflow_call:
    runs-on: ubuntu-latest
    steps:
      - name: echo back client payload
        run: echo ${{ fromJSON(inputs) }}
