name: Build and Publish Docker

on:
  repository_dispatch:
    types: [build-tenant]

jobs:
  run_if_failure:
    runs-on: ubuntu-latest
    steps:
      - name: echo back
        run: echo  ${{ github.event.client_payload }}
