name: Test repo dispatch

on:
  repository_dispatch:
    types: [test-run]

jobs:
  run_if_failure:
    runs-on: ubuntu-latest
    steps:
      - name: echo back client payload
        run: echo ${{ github.event.client_payload }}
