---
name: Test Trigger
'on':
  workflow_dispatch:
    inputs:
      tenant:
        description: Which tenant to publish
        required: true
        type: choice
        options:
          - public
jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest
    reuse-stuff:
      - uses: sjungling/test-actions/.github/workflows/test.yml@main
        with:
          tenant: ${{ github.event.inputs.tenant }}
          ref: ${{ github.event.ref }}
