---
name: Test Trigger
'on':
  workflow_dispatch:
    inputs:
      tenant:
        description: Which tenant to publish
        required: true
        type: choice
        options:
          - public
jobs:
  build-and-publish-docker:
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    environment: '${{ github.event.inputs.tenant }}'
    steps:
      call-workflow-passing-data:
        uses: ./.github/workflows/test.yml
        with:
          tenant: ${{ github.event.inputs.tenant }}
          ref: ${{ github.event.ref }}
        secrets:
          token: '${{ secrets.GITHUB_TOKEN }}'

        # uses: ./.github/workflows/workflow-2.yml
        # with:
        #   token: '${{ secrets.GITHUB_TOKEN }}'
        #   repository: '${{ github.repository }}'
        #   event-type: test-run
        #   client-payload: '{"tenant": "${{ github.event.inputs.tenant }}", "github": { "ref": "${{ github.event.ref }}"}}'
